Rustscan
ThePorgs/Exegol-resources pull request #27
Opened 2024-04-30 23:29 UTC by lap1nou

Greetings,

This PR aims to add `rustscan` in resources so one can drop the binary on target machine.

I personally find it useful to have a port scanner available that one can drop on a target.

Regards.

2024-08-31 18:35 UTC, Dramelac requested changes
Thank you for the PR!
Every release dont always have the asset mentionned here unfortunately.
It was `[...]-windows.zip` but the latest release use `[...]-windows.tar.xz`. Can you update this before merging ? Thanks !

2025-01-24 18:31 UTC, lap1nou commented
Hey @Dramelac,

Sorry for the late answer, which tag are you talking about ? I see the file `rustscan-$VERSION-x86_64-windows.zip` for each latest release.

![image](https://github.com/user-attachments/assets/79280e8f-d87a-4c52-aa44-214f2baa6292)

2025-01-24 21:40 UTC, lap1nou commented
This should do the trick I think.

2025-02-22 13:47 UTC, ShutdownRepo commented
@lap1nou theres still one comment to check (the `chkfs` command), but apart from that we should be good to go
Can you take a look at the comment pending?

2025-02-22 13:51 UTC, lap1nou commented
@ShutdownRepo Hey sure no problem, but I must be blind because I can't see the comment you are mentioning

2025-04-21 16:17 UTC, merged