Add PowerSharpPack
ThePorgs/Exegol-resources pull request #34
Opened 2024-08-28 11:19 UTC by cHJlaXpoZXI

Hi ! A little PR to add PowerSharpPack to resources folder !

It's great to have Powershell version of all C# binaries ! I found it really usefull with evil-WinRM for example ! You can also execute it in memory with a HTTP server and IEX command !

Thanks :)

2024-08-31 18:26 UTC, Dramelac requested changes
Thank you for the PR!
There is just a missing update to the `update-resources.sh` file. The new submodule must be added to the `update_submodules` function.

2024-09-01 13:47 UTC, cHJlaXpoZXI commented
> Thank you for the PR! There is just a missing update to the `update-resources.sh` file. The new submodule must be added to the `update_submodules` function.

Oupsi ! It's added :)

2024-09-04 13:53 UTC, ShutdownRepo approved these changes

2024-09-04 13:53 UTC, ShutdownRepo commented
Thank you @cHJlaXpoZXI, merging!

2024-09-04 13:53 UTC, merged